global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

scrape_configs:
  # Monitoramento da aplicação Spring Boot
  - job_name: 'pedidos-app'
    static_configs:
      - targets: ['app:8080']
    metrics_path: '/api/actuator/prometheus'  # Corrigido: /api + /actuator/prometheus
    scrape_interval: 15s
    scrape_timeout: 10s

  # Monitoramento do Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Monitoramento do PostgreSQL (se tiver exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Monitoramento do Redis (se tiver exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Monitoramento do sistema (se tiver node-exporter)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s